export const investments = [
  {
    name: 'Tesouro Direto IPCA+',
    description: 'TD 2045',
    amount: 152000,
    yield: 12.5,
    category: 'Fixed Income',
    investedDate: '2023-05-14',
    maturityDate: '2045-08-15',
    icon: 'account_balance',
    iconColor: 'primary',
  },
  {
    name: 'CDB Banco Itaú Unibanco',
    description: '110% CDI',
    amount: 45300,
    yield: 10.2,
    category: 'Fixed Income',
    investedDate: '2024-01-02',
    maturityDate: '2026-01-02',
    icon: 'apartment',
    iconColor: 'secondary',
  },
  {
    name: 'IVVB11 ETF',
    description: 'S&P 500 Index',
    amount: 280900,
    yield: 18.4,
    category: 'Variable Income',
    investedDate: '2021-11-10',
    maturityDate: null,
    icon: 'monitoring',
    iconColor: 'tertiary',
  },
  {
    name: 'Ethereum (ETH)',
    description: 'Digital Asset',
    amount: 88400,
    yield: -4.2,
    category: 'Variable Income',
    investedDate: '2022-07-22',
    maturityDate: null,
    icon: 'token',
    iconColor: 'primary',
  },
  {
    name: 'HGLG11 - Logística',
    description: 'Real Estate Fund',
    amount: 32100,
    yield: 8.9,
    category: 'Variable Income',
    investedDate: '2023-08-05',
    maturityDate: null,
    icon: 'house',
    iconColor: 'primary',
  },
];
